// go run gen.go
// MACHINE GENERATED BY THE ABOVE COMMAND; DO NOT EDIT.

package fields

var CertFields = FieldDict{
	Key{EnterpriseID: 6871, FieldID: 14}:    {Name: "initialTCPFlags", Decoder: Unsigned8},
	Key{EnterpriseID: 6871, FieldID: 15}:    {Name: "unionTCPFlags", Decoder: Unsigned8},
	Key{EnterpriseID: 6871, FieldID: 21}:    {Name: "reverseFlowDeltaMilliseconds", Decoder: Signed32},
	Key{EnterpriseID: 6871, FieldID: 22}:    {Name: "silkTCPState", Decoder: Unsigned8},
	Key{EnterpriseID: 6871, FieldID: 30}:    {Name: "silkFlowType", Decoder: Unsigned8},
	Key{EnterpriseID: 6871, FieldID: 31}:    {Name: "silkFlowSensor", Decoder: Unsigned8},
	Key{EnterpriseID: 6871, FieldID: 33}:    {Name: "silkAppLabel", Decoder: Unsigned8},
	Key{EnterpriseID: 6871, FieldID: 16398}: {Name: "reverseInitialTCPFlags", Decoder: Unsigned8},
	Key{EnterpriseID: 6871, FieldID: 16399}: {Name: "reverseUnionTCPFlags", Decoder: Unsigned8},
	Key{EnterpriseID: 6871, FieldID: 100}:   {Name: "expiredFragmentCount", Decoder: Unsigned32},
	Key{EnterpriseID: 6871, FieldID: 101}:   {Name: "assembledFragmentCount", Decoder: Unsigned32},
	Key{EnterpriseID: 6871, FieldID: 102}:   {Name: "meanFlowRate", Decoder: Unsigned32},
	Key{EnterpriseID: 6871, FieldID: 103}:   {Name: "meanPacketRate", Decoder: Unsigned32},
	Key{EnterpriseID: 6871, FieldID: 104}:   {Name: "flowTableFlushEventCount", Decoder: Unsigned32},
	Key{EnterpriseID: 6871, FieldID: 105}:   {Name: "flowTablePeakCount", Decoder: Unsigned32},
}

func init() {
	if err := RegisterFields(CertFields); err != nil {
		panic(err)
	}
}
