- module: cyberarkpas
  audit:
    enabled: true

    # Set which input to use between udp (default), tcp, tls or file.
    # TODO
    # var.input: udp
    # var.syslog_host: localhost
    # var.syslog_port: 9527

    # Set paths for the log files when file input is used.
    # var.paths:

