// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License;
// you may not use this file except in compliance with the Elastic License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package palo_alto

import (
	"github.com/elastic/beats/libbeat/asset"
)

func init() {
	if err := asset.SetFields("filebeat", "palo_alto", asset.ModuleFieldsPri, AssetPaloAlto); err != nil {
		panic(err)
	}
}

// AssetPaloAlto returns asset data.
// This is the base64 encoded gzipped contents of module/palo_alto.
func AssetPaloAlto() string {
	return "eJxsjjsOwjAQRHufYsqkCAdwQYXoUBp6ZOF1sNhkLXtT5PbIIYiPeOVo9GY63GmxSI7l4ljFABqV6TvyVK45Jo0yWewNAJzEz0wIktE05/7Qt60BQiT2xa6NDpMbf0QVXRJZDFnmtCV/9JXjKkPIMkJv9BaBZSi7rfc5+eQ1XF+ZRwAAAP//HNNBZA=="
}
