// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License;
// you may not use this file except in compliance with the Elastic License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package palo_alto

import (
	"github.com/elastic/beats/libbeat/asset"
)

func init() {
	if err := asset.SetFields("filebeat", "palo_alto", asset.ModuleFieldsPri, AssetPaloAlto); err != nil {
		panic(err)
	}
}

// AssetPaloAlto returns asset data.
// This is the base64 encoded gzipped contents of module/palo_alto.
func AssetPaloAlto() string {
	return "eJx0jjGuwjAQBXuf4pVJkX8AF79CdCgNPYrIJlhsvJa9KXJ75CiAg+CVo/WMG9xpsQgdy6VjFQOoU6Y96ildowvqxFv8GwA4ST8zYZCIqjq3h7auDTA44j7Z9aKB76YPUZ4ugSzGKHPYyBd93nGVYYgyQW/0FoFlTH/bXZkss/lPL/issvixgD/Cebvn5hEAAP//SVtQig=="
}
