// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License;
// you may not use this file except in compliance with the Elastic License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package o365

import (
	"github.com/elastic/beats/libbeat/asset"
)

func init() {
	if err := asset.SetFields("filebeat", "o365", asset.ModuleFieldsPri, AssetO365); err != nil {
		panic(err)
	}
}

// AssetO365 returns asset data.
// This is the base64 encoded gzipped contents of module/o365.
func AssetO365() string {
	return "eJzMmFtv3LoRx9/9KQj0wUkByiR1IbkBirp23C4ax0bWafpmUORwzVorqhTl482nP9AaPr5EyoU+wTl6FMX5cYZ/zoyI0TVsF8jnVbmHUHSxgQU6s9ZpQHfvDPQ6uC463y7Q3/YQQujUm6EBZH1AV6o1jWvXqPHrHtngN49mZ3sIWQeN6Re7eXcPRq3awB1TDcbFR2MIxW0HC7QOfuievDdg1dDEy529BbKq6eHZB1+s8+E52a3i+frQqWrVGjbQRnR4vkS71ew8yZ7M/9KHBy8OdfThGe3OBxWC2j4bmbL0YGt5/Gzg3tQ1bH/xwXwx+he4VZtu3LJhn5cllIQoXGmS46KqCa7LvMZMMMvynBeQ1/sz4IttB8loMh+XI99GuI3L59O/ZvqxT7WoVC1Nga22FBc1pVgoUmGuhJW0Lritzf48ftkdGhOg7xPxXGa0lBklGS3pDKfrkr2btdg4rUYdJ1sWsgagluMSKsCFEQpLmxsM2lSEslIaxWfon4cAhzq6Gzh2AcYobt/eQBsnJPJ9q6GTnKPGQRt//+jd2V2e/7wdP/IhQPOy/akkq/NcWqwJrbAihGDLSoulJIrwmgGhc/QAO/SF26Rtx7DPCCOYMEzZBaOLXCzyGS0cDX30m4+t+/8Aia5ehAEmbR+rqJIlNeyP05dt79ZXsV8N9W+Zf9qRnYBXfgg6lbe6UgHOvWvjDOE2QmvAnAffQYgO+uyvkyhf/w90nLURWtUcap2asmbDnazUnGiurNbY8sLgoi4VFlIA1sCZUTIXVS2mQ7LcjHnMxV3oEunv/YztNkJYbfsImz7ZNZWXIAWpsRA14CIvciwrSXHFZMFzIFSKfBYf1B0+mc6FYkpVJS4Jq3BBWYElJwoTAqQymhtLyAw9wuYFR+fENTBt+J3r00s1qytlWG0wsYbjoiwrLLWQWEkuCk5EWYvyK9gIL0s0wz63pFJ1rnBtpMAFNTlWpGZYGcaJ4RQKM6PUd37t27chzPRxU+j7qafeOOuenvsfP/lnu6Fkz0tLZJ7nCouCaVxwo7CiJcclN4pxq2utZkJ/1kHYlZNE8scewju/XoNZzqTes7BWrfv8snKZ3gY+xr9XySUzQh97B5vMtxung++9jZn2mzmoW7tWRdeuVxBu4Ptl9ZT6r7f0/AOhhJ3+I2dMoFe0zBjJGGcyI5S/nqafq6A2ECEklKAPoH0w6a1eOWO1H5q4iioOqZ34atAawMDMNq9cTN1aU1JBtNU4L7jERWEqXBeUYKGlKJUWsoCZKjBCP4YmkXsVY9cvDg7upYU326wfS2U3dhmjuA46CL1vVXOg+nB5/93lIwlejl/NLG7X7Yy5ftea9OlnvGvX30K84GStdABo+ysfs2+APuya7psXhPzY62H81+9nMEPX+RAvnL6G9GQ8bftChTXEP8M1wY8Xi596TXAXmD/unmCsYIdraKf35tvkU//ZNY06KDOCXp0q7dro+6s3uw61QadKo7MV+i8afyiLNyjcLDjLyGv0T9DX/oARSgglFJ24ANbfHoyD8+tM73T78PcfK2Ej7t/wXJbfy6OE5IwQIivJ6UlZJsCTa9C0zP4DITkFTl9gfII6/XpGl1oWdY1FLitccKKx4IZjIaW0RUG0yWdk8MmH68arVPDU7c4DaO/XAAAA//9aJYP2"
}
